import { writeFileSync, existsSync, readFileSync, mkdirSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { parsePdb } from '../src/parser/pdb.js';
import { parseDsspMmcif } from '../src/parser/dssp-mmcif.js';
import { mergeProteinData } from '../src/parser/merge.js';
import type { ProteinData } from '../src/types.js';

const PROTEINS: { id: string }[] = [
  { id: '3k19' },
  { id: '2omf' },
  { id: '7ahl' },
  { id: '2j1n' },
  { id: '5g53' },
];

async function fetchText(url: string, retries = 4): Promise<string> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < retries; attempt++) {
    if (attempt > 0) await new Promise((r) => setTimeout(r, 1000 * 2 ** attempt));
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
      return await res.text();
    } catch (err) {
      lastErr = err;
      console.warn(`  attempt ${attempt + 1} failed: ${err instanceof Error ? err.message : err}`);
    }
  }
  throw lastErr;
}

/**
 * Usage: `tsx scripts/prebuild-demo.ts [--from <dir>] [--out <file>]`
 *
 * By default each protein is fetched from OPM and PDB-REDO and written to
 * `src/demo-data.ts`. With `--from`, `<dir>/<id>.pdb` and `<dir>/<id>.dssp.cif`
 * are read instead (e.g. `examples/`, for offline builds and the E2E tests);
 * proteins with no files there are left out.
 */
async function main(): Promise<void> {
  const { values: args } = parseArgs({
    options: { from: { type: 'string' }, out: { type: 'string' } },
  });
  const outPath = args.out
    ? resolve(args.out)
    : fileURLToPath(new URL('../src/demo-data.ts', import.meta.url));
  const typesPath = fileURLToPath(new URL('../src/types.js', import.meta.url));
  let typesImport = relative(dirname(outPath), typesPath).replaceAll('\\', '/');
  if (!typesImport.startsWith('.')) typesImport = `./${typesImport}`;
  const results: Record<string, ProteinData> = {};
  let anyFailed = false;

  for (const { id } of PROTEINS) {
    let load: () => Promise<[string, string]>;
    if (args.from) {
      const pdbPath = resolve(args.from, `${id}.pdb`);
      const dsspPath = resolve(args.from, `${id}.dssp.cif`);
      if (!existsSync(pdbPath) || !existsSync(dsspPath)) continue;
      process.stdout.write(`Reading ${id}… `);
      load = async () => [readFileSync(pdbPath, 'utf8'), readFileSync(dsspPath, 'utf8')];
    } else {
      process.stdout.write(`Fetching ${id}… `);
      const pdbUrl = `https://opm-assets.storage.googleapis.com/pdb/${id.toLowerCase()}.pdb`;
      const dsspUrl = `https://pdb-redo.eu/dssp/get?pdb-id=${id}&format=mmcif`;
      load = () => Promise.all([fetchText(pdbUrl), fetchText(dsspUrl)]);
    }

    try {
      const [pdbText, dsspText] = await load();
      const chains = parsePdb(pdbText);
      const ssSegments = parseDsspMmcif(dsspText);
      results[id] = mergeProteinData(id, chains, ssSegments);
      const summary = results[id].chains.map((c) => `${c.chainId}:${c.residueCount}aa`).join(', ');
      console.log(`done (${summary})`);
    } catch (err) {
      console.warn(`skipped (${err instanceof Error ? err.message : err})`);
      anyFailed = true;
    }
  }

  if (anyFailed && Object.keys(results).length === 0) {
    if (existsSync(outPath)) {
      console.warn('All fetches failed — keeping existing demo-data.ts');
      return;
    }
    throw new Error('All fetches failed and no existing demo-data.ts to fall back on');
  }

  if (anyFailed) {
    console.warn('Some proteins could not be fetched — writing partial update');
  }

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(
    outPath,
    `import type { ProteinData } from '${typesImport}';

// Generated by scripts/prebuild-demo.ts — do not edit by hand
// Run \`npm run prebuild:demo\` to regenerate from live sources
export const proteins: Record<string, ProteinData> = ${JSON.stringify(results, null, 2)};
`,
  );
  console.log(`Wrote ${relative(process.cwd(), outPath)}`);
}

main().catch((err: unknown) => {
  console.error('prebuild-demo failed:', err);
  process.exit(1);
});
