import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parsePdb } from '../src/parser/pdb.js';
import { parseDsspMmcif } from '../src/parser/dssp-mmcif.js';
import { mergeProteinData } from '../src/parser/merge.js';
import type { ProteinData } from '../src/types.js';

const PROTEINS: { id: string; simId: string }[] = [
  { id: '3k19', simId: '3k19_default_dppc' },
  { id: '2omf', simId: '2omf_default_dppc' },
  { id: '7ahl', simId: '7ahl_default_dppc' },
];

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  return res.text();
}

async function main(): Promise<void> {
  const results: Record<string, ProteinData> = {};

  for (const { id, simId } of PROTEINS) {
    process.stdout.write(`Fetching ${id}… `);
    const pdbUrl = `https://memprotmd.bioch.ox.ac.uk/data/memprotmd/simulations/${simId}/files/structures/at.pdb`;
    const dsspUrl = `https://pdb-redo.eu/dssp/get?pdb-id=${id}&format=mmcif`;

    const [pdbText, dsspText] = await Promise.all([fetchText(pdbUrl), fetchText(dsspUrl)]);

    const chains = parsePdb(pdbText);
    const ssSegments = parseDsspMmcif(dsspText);
    results[id] = mergeProteinData(id, chains, ssSegments);

    const summary = results[id].chains.map((c) => `${c.chainId}:${c.residueCount}aa`).join(', ');
    console.log(`done (${summary})`);
  }

  const outPath = fileURLToPath(new URL('../src/demo-data.ts', import.meta.url));
  writeFileSync(
    outPath,
    `import type { ProteinData } from './types.js';

// Generated by scripts/prebuild-demo.ts — do not edit by hand
// Run \`npm run prebuild:demo\` to regenerate from live sources
export const proteins: Record<string, ProteinData> = ${JSON.stringify(results, null, 2)};
`,
  );
  console.log('Wrote src/demo-data.ts');
}

main().catch((err: unknown) => {
  console.error('prebuild-demo failed:', err);
  process.exit(1);
});
