/**
 * Spike data generator (THROWAWAY — Phase 0 of issue #22).
 *
 * Fetches OPM-aligned PDBs (already in the membrane frame) and extracts Cα
 * coordinates plus secondary structure straight from the HELIX/SHEET records in
 * the file. This sidesteps the pdb-redo DSSP endpoint (blocked in this
 * environment) and keeps the visual spike fully self-contained.
 *
 * Output: src/spike/spike-data.ts
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parsePdb } from '../src/parser/pdb.js';
import { mergeProteinData } from '../src/parser/merge.js';
import type { RawSSSegment } from '../src/parser/types.js';
import type { ProteinData } from '../src/types.js';

const PROTEINS = [
  { id: '5g53', note: 'A2A adenosine receptor (+ G-protein) — 7TM helical bundle' },
  { id: '2j1n', note: 'OmpC osmoporin — 16-strand β-barrel' },
];

/** Parse HELIX (helix) and SHEET (strand) records into RawSSSegment runs. */
function parseSsRecords(pdb: string): RawSSSegment[] {
  const out: RawSSSegment[] = [];
  for (const line of pdb.split('\n')) {
    const rec = line.slice(0, 6);
    if (rec === 'HELIX ') {
      // Columns per PDB spec: initChainID 19, initSeqNum 21-25, endChainID 31,
      // endSeqNum 33-37.
      const chainId = line[19];
      const start = Number.parseInt(line.slice(21, 25), 10);
      const end = Number.parseInt(line.slice(33, 37), 10);
      if (chainId && chainId !== ' ' && Number.isFinite(start) && Number.isFinite(end)) {
        out.push({ chainId, start, end, type: 'helix' });
      }
    } else if (rec === 'SHEET ') {
      // initChainID 21, initSeqNum 22-26, endChainID 32, endSeqNum 33-37.
      const chainId = line[21];
      const start = Number.parseInt(line.slice(22, 26), 10);
      const end = Number.parseInt(line.slice(33, 37), 10);
      if (chainId && chainId !== ' ' && Number.isFinite(start) && Number.isFinite(end)) {
        out.push({ chainId, start, end, type: 'strand' });
      }
    }
  }
  return out;
}

async function fetchText(url: string, retries = 4): Promise<string> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < retries; attempt++) {
    if (attempt > 0) await new Promise((r) => setTimeout(r, 1000 * 2 ** attempt));
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.text();
    } catch (err) {
      lastErr = err;
    }
  }
  throw lastErr;
}

async function main(): Promise<void> {
  const results: Record<string, ProteinData> = {};
  for (const { id } of PROTEINS) {
    process.stdout.write(`Fetching ${id}… `);
    const pdb = await fetchText(`https://opm-assets.storage.googleapis.com/pdb/${id}.pdb`);
    const chains = parsePdb(pdb);
    const ss = parseSsRecords(pdb);
    results[id] = mergeProteinData(id, chains, ss);
    const summary = results[id].chains
      .map((c) => `${c.chainId}:${c.residueCount}aa/${c.segments.length}ss`)
      .join(', ');
    console.log(`done (${summary})`);
  }

  const out = fileURLToPath(new URL('../src/spike/spike-data.ts', import.meta.url));
  const banner =
    '// GENERATED by scripts/prebuild-spike.ts — throwaway spike data (issue #22).\n' +
    '// Do not edit by hand.\n';
  writeFileSync(
    out,
    `${banner}import type { ProteinData } from '../types.js';\n\n` +
      `export const spikeProteins: Record<string, ProteinData> = ${JSON.stringify(results)};\n`,
  );
  console.log(`Wrote ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
